controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster


bicycle_steering_controller:
  ros__parameters:
    type: bicycle_steering_controller/BicycleSteeringController

    traction_joints_names: ['virtual_rear_wheel_joint']
    steering_joints_names: ['virtual_front_wheel_joint']
    wheelbase: 0.343 # front-to-back distance between wheels, is updated
    traction_wheel_radius: 0.0685 # is updated 

    reference_timeout: 0.1 # stops the controller if it stops receiving instructions (velocity) 

    open_loop: false # open loop = DOESN't check with encoders to ensure the car is following our instructions
                     #               and instead just continuously sends instructions without checking 
    position_feedback: false # default false, uses encoders to give velocity feedback
    velocity_rolling_window_size: 10 # number of velocity samples to average to compute twist velocities     
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: false
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]

pose_broadcaster:
  ros__parameters:
    type: pose_broadcaster/PoseBroadcaster
    pose_name: fused_odom
    frame_id: odom
    tf.enable: false
    tf.child_frame_id: base_link

