twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      navigation:
        topic: cmd_vel_nav_stamped # the input from nav2, after being stamped
        timeout: 0.5
        priority: 10
      keyboard:
        topic: cmd_vel_manual # TODO: whatever we're using for manual control, see https://articulatedrobotics.xyz/tutorials/mobile-robot/applications/teleop for guide
        timeout: 0.5
        priority: 100 # means that IF the manual control is used, it always overrides nav2